### ISSUE TITLE
Font file address error at build time

### ISSUE THREAD

**Issue by NimaKaviyani** [noreading/bootstrap5-webpack-boilerplate#238]
Hello,
The font file addresses are wrong at build time. The problem is in the `google-fonts.scss` file on `lines 40-43`. Please check these lines and correct the addresses.
**version:** `v1.0.1`

![boilerplate](https://github.com/noreading/bootstrap5-webpack-boilerplate/assets/32512803/246e6875-8315-467a-a6b0-fb58c158146b)

```SCSS
@mixin googleFont($font) {
  $fontFamily: map-get($font, "name");
  $folderName: map-get($font, "folder");
  $fileName: map-get($font, "files");
  $weights: map-get($font, "weights");
  @each $weight in $weights {
    $weightName: map-get($fontWeightNames, $weight);
    @font-face {
      font-family: "#{$fontFamily}";
      font-weight: $weight;
      font-display: swap;
      src: url("../../fonts/#{$folderName}/#{$fileName}-#{$weightName}.eot"); /* IE 9 - 11 */
      src: url("../../fonts/#{$folderName}/#{$fileName}-#{$weightName}.eot?#iefix") format('embedded-opentype'), /* IE 9 - 11 */
      url("../../fonts/#{$folderName}/#{$fileName}-#{$weightName}.woff2") format('woff2'),
      url("../../fonts/#{$folderName}/#{$fileName}-#{$weightName}.woff") format('woff');
    }
  }
}
```
